---
title: Writing Functions
date: '2024-03-20'
categories:
- slides
- Week08
---

# We have read

[Writing Functions](https://srvanderplas.github.io/stat-computing-r-python/part-gen-prog/05-functions.html)

Why do we need functions?

-   Re-usability

-   Readability

-   Maintainability

## Writing functions {.scrollable}

-   Syntax

    -  R:  `function_name <- function(params){ }`

    -  Python:  `def(params):`

-   parameter vs argument

    -   passing in more than one arguments

        -   follow the order of parameters    
        `(x_, y_) ->func(x, y)`

        -   specify by parameters     
        `func(x=x_, y = y_)`

## Writing functions {.scrollable}

-   Input validation

    -   Handle exceptions

        -   data type

        -   invalid data

    -   `stopifnot()` and `try...except...`

-   Scope

    -   Lexical scope: the area that is between the braces/ indented region

    -   "Rewrite"

    -   [python visualizer](https://pythontutor.com/visualize.html#mode=edit)    
    [See a simple function in action](https://pythontutor.com/render.html#code=def%20rescale01%28x%29%3A%0A%20%20xmin,%20xmax%20%3D%20%5Bmin%28x%29,%20max%28x%29%5D%0A%20%20return%20%5B%28i%20-%20xmin%29/%28xmax%20-%20xmin%29%20for%20i%20in%20x%5D%0A%0Ax%20%3D%20%5B1,%202,%203,%204,%205,%206,%207,%2010%5D%0A%0Arescale01%28x%29&cumulative=false&curInstr=18&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false)

::: r-fit-text
# Next Time

-   [version control](https://srvanderplas.github.io/stat-computing-r-python/part-tools/05-git-and-github.html)

-   Before next week: **Sign up for Github Classroom**

-   Seminar of interest: Dr. Heike Hofmann will talk about the practical side of building data processing pipelines. Hardin 901, 11:30 - 12:20, with lunch afterwards.     
Earn 2 points of extra credit on a reading quiz. 

:::

# Homework 6 {.scrollable}

-   Download and save [Homework6 raw content](https://raw.githubusercontent.com/srvanderplas/unl-stat151/main/homework/06-fizzbuzz.qmd)

    -   Click the link

    -   Copy the raw content

    -   Save to a **Quarto** file under Source mode

    -   Name the file as ***06-Lastname-Firstname.qmd***

    -   Submit in .qmd file

## Homework 6 {.scrollable}

-   `print()` function doesn't have a return value

-   Pay attention to the data type
